# Generated by Django 5.2.7 on 2025-10-05 01:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booking_time'], 'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AddField(
            model_name='booking',
            name='num_seats',
            field=models.PositiveIntegerField(default=1, help_text='Number of seats to book', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_email',
            field=models.EmailField(help_text='Email address for booking confirmation', max_length=254),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_name',
            field=models.CharField(help_text='Full name of the attendee', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(help_text='Event date and time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text='Provide a detailed description of the event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(help_text='Enter the event name', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='seats_available',
            field=models.PositiveIntegerField(help_text='Number of seats available for booking', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('event', 'user_email')},
        ),
    ]
